### ISSUE TITLE
externVar from latent class growth model with no random effect

### ISSUE THREAD

**Issue by rossneville** [CecileProust-Lima/lcmm#274]
Dear Prof. Proust-Lima

Does the externVar command work with a latent class model with no random effect?

I get an error when I try to run the following model:

# estimation of the first model (ordinal latent class growth model)

paquid$age65 <- paquid$age - 65
mthresholds <- lcmm(HIER ~ age65 * male, subject='ID', data=paquid, link='thresholds')
mthresholds2 <- lcmm(HIER ~ age65 * male, subject='ID', mixture=~ age65,ng=2,data=paquid,
link='thresholds',B=random(mthresholds))

# estimation of an external model with a (pseudo) time-fixed outcome
# I consider here the last value of IST during the follow-up

library(dplyr)
paq <- paquid %>%
group_by(ID) %>% 
mutate(agemax = max(age)) %>%
ungroup %>%
mutate(ISTlast = ifelse(age==agemax,IST,NA))

# with only 10 bootstrap as just for the illustration
ext0 <- externVar(mthresholds2,fixed= ISTlast ~ 1, mixture=~1,
data=paq,method="conditional",M = 10,varest = "paramBoot")
summary(ext0)

When I run this model I get the following error:

Error in terms.formula(object, data = data) : 
  argument is not a valid model

As you know, since you shared this reproducible example with me to resolve another issue, this series of code runs fine when the random effect (random = ~1) is included in the mthresholds and mthresholds2 models.

Perhaps there is very sensible reason why this is the case (eg, the random effects are needed to account for latent class uncertainty in the external model).

I would appreciate any direction you can provide.

Regards
ross

**Comment by VivianePhilipps** [comment]
Hello Ross,

thank you for the example, there was indeed a bug in the externVar function.
I just committed a correction. Could you please try it ?
Thanks,

Viviane

**Comment by rossneville** [comment]
Hi Viviane
Thanks for the response and work to try to correct the bug. 
I just uninstalled lcmm and reinstalled it from github using the following updated  example.
However, I still get the same exact error.
Perhaps I have not managed the uninstall and reinstall process properly from github.
Regards
Ross

remove.packages("lcmm")
remotes::install_github("https://github.com/CecileProust-Lima/lcmm.git")
library(lcmm)
library(dplyr)

paquid$age65 <- paquid$age - 65
mthresholds <- lcmm(HIER ~ age65 * male, subject='ID', data=paquid, link='thresholds')
mthresholds2 <- lcmm(HIER ~ age65 * male, subject='ID', mixture=~ age65,ng=2,data=paquid,
                     link='thresholds',B=random(mthresholds))

#estimation of an external model with a (pseudo) time-fixed outcome
#I consider here the last value of IST during the follow-up

paq <- paquid %>%
  group_by(ID) %>%
  mutate(agemax = max(age)) %>%
  ungroup %>%
  mutate(ISTlast = ifelse(age==agemax,IST,NA))

# with only 10 bootstrap as just for the illustration
ext0 <- externVar(mthresholds2,fixed= ISTlast ~ 1, mixture=~1,
                  data=paq,method="conditional",M = 10,varest = "paramBoot")
summary(ext0)

**Comment by rossneville** [comment]
Hi Viviane

I just uninstalled and reinstalled and ran the programme again. 

I don't get the error anymore. However, ext0 didn't estimate any standard errors for the latent group means for ISTlast.

So something has progressed here.

I then tried to run the model again with some starting values for "intercept class1", "intercept class2", and the residual standard error "stderr". 

This seemed to work.

Perhaps you could confirm if working properly

Here's the code I ran that seemed to work:

remove.packages("lcmm")
library(devtools)
remotes::install_github("https://github.com/CecileProust-Lima/lcmm.git")
library(lcmm)
library(dplyr)

paquid$age65 <- paquid$age - 65
mthresholds <- lcmm(HIER ~ age65 * male, subject='ID', data=paquid, link='thresholds')
mthresholds2 <- lcmm(HIER ~ age65 * male, subject='ID', mixture=~ age65,ng=2,data=paquid,
link='thresholds',B=random(mthresholds))

#estimation of an external model with a (pseudo) time-fixed outcome
#I consider here the last value of IST during the follow-up

paq <- paquid %>%
group_by(ID) %>%
mutate(agemax = max(age)) %>%
ungroup %>%
mutate(ISTlast = ifelse(age==agemax,IST,NA))

with only 10 bootstrap as just for the illustration
ext0 <- externVar(mthresholds2,fixed= ISTlast ~ 1, mixture=~1,
data=paq,method="conditional",M = 10,varest = "paramBoot")
summary(ext0)

ext0 <- externVar(mthresholds2,fixed= ISTlast ~ 1, mixture=~1,
                  data=paq,method="conditional",M=10,varest = "paramBoot")
summary(ext0)
binit <- ext0$best

# final model with only 10 bootstrap as just for the illustration
ext1 <- externVar(mthresholds2,fixed= ISTlast ~ 1, mixture=~1,
                  data=paq,method="conditional",M=10,varest = "paramBoot", B=binit)
summary(ext1)

Regards
Ross

**Comment by rossneville** [comment]
Dear Viviane
This is great news.
Thanks for the update.
Regards
Ross

Dr Ross D. Neville, PhD, ProfCert University Teaching and Learning
Head of Subject - Sport Management
School of Public Health, Physiotherapy and Sport Science
University College Dublin (UCD)
Room G6 - Woodview House
Belfield, Dublin 4
***@***.***
+353 (0) 1 716 3419

**Comment by rossneville** [comment]
Dear Viviane,

I have updated my input model for use in externvar and I am now receiving an error:

Error in chol.default(varcov): the leading minor of order 3 is not positive

My input model is:

m1 <- lcmm(fixed = y ~ ns(Age_rescaled, knots = c(0.33, 0.67)), mixture = ~ns(Age_rescaled, 
    knots = c(0.33, 0.67)), random = ~ns(Age_rescaled, knots = c(0.33, 
    0.67)), subject = "ID", ng = 3, nwg = T, link = "thresholds", 
    data = df)

df1 <- df %>%
group_by(ID) %>%
mutate(agemax = max(Age_rescaled)) %>%
ungroup %>%
mutate(DVlast = ifelse(Age_rescaled==agemax,DV,NA))

This model converged when I checked (m1$conv), and all of the usual lcmm functions work fine with it.

Then, my externvar model is: 

ext1 <- externVar(m1,fixed= AttentionLAST ~ 1, mixture=~1,
                  data=df1,method="conditional",M=10,varest = "paramBoot")

This model gives the error.

Perhaps it has something to do with the proportion of convergence on bootstrap iterations, as shown in **bold** below (70%).

The m1 input model seems to work fine for external outcomes where I have observations at each level of Age_rescaled. However, this model where I only have an observation for AttentionLAST at the final Age_rescaled observation seems to be having problems running.

Is there any advice you could give?

Regards
Ross

**Secondary linear mixed model 
     fitted by maximum likelihood method 
     primary model variance accounted for through parametric boostrap 
 
externVar(model = mthresholds3, fixed = ISTlast ~ 1, mixture = ~1, 
    data = paq, method = "conditional", varest = "paramBoot", 
    M = 10)
 
Statistical Model: 
     Dataset: paq 
     Number of subjects: 412 
     Number of observations: 412 
     Number of observations deleted: 1838 
     Number of latent classes: 3 
     Number of parameters: 4  
 
Iteration process: 
 
     Proportion of convergence on bootstrap iterations (%)= 70 
 
Goodness-of-fit statistics: 
     maximum log-likelihood: -1349.77  
     AIC: 2712.09  
     BIC: 2728.17**

**Comment by rossneville** [comment]
Dear Cecile and Vivianne

Continuing the reproducible example from September 23rd above, and the final model in particular (ext1), ...

ext1 <- externVar(mthresholds2,fixed= ISTlast ~ 1, mixture=~1,
data=paq,method="conditional",M=10,varest = "paramBoot", B=binit)
summary(ext1)

... is it possible with lcmm commands to conduct a hypothesis test to compare the marginal predictions between latent classes?

I can use the predictY() command to compute the class-specific 50%, 2.5% and 97.5% percentiles of the posterior distribution.

However, do I need to use ext1$pred[4] to extract the the pred_ss values for each class, and what would I do from there to get an estimate of their difference in the distribution of ISTlast between the two groups and its uncertainty (i.e., something like a confidence interval for this difference)?

Appreciate any support or links to specific guidance and vignettes you can provide.

Thanks
Ross

**Comment by VivianePhilipps** [comment]
Hi,

to get a confidence interval around a difference of subject specific predictions, you have to implement it with a Monte Carlo samples. I gave an example in issue #278.

If it is around the marginal predictions, here you just want to test the difference between the 2 intercepts. So you can use the WaldMult function:
`
WaldMult(ext1, pos = c(1,2), contrasts = c(1,-1))`

Best,

Viviane

**Comment by rossneville** [comment]
Thanks Viviane

In the meantime I had used the model$best and model$V output to reconstruct
the variance-covariance matrix and estimated the difference in the latent
process scale using the mean and variance of the differences, derived from
the reconstructed matrix, followed by a Monte Carlo simulation to
approximate the posterior distribution and calculate the 95% credible
interval.
What do you think of that as an approach?

It’s obviously not ideal, since the outcomes are in the latent process
scale.

However, with this approach I can also estimate the difference in slopes
too (rather than just difference in predicted means).

You approach only gives the difference in predicted means, as far as I can
tell.

Thanks
Ross

Dr Ross D. Neville, PhD, ProfCert University Teaching and Learning
Head of Subject - Sport Management
School of Public Health, Physiotherapy and Sport Science
University College Dublin (UCD)
Room G6 - Woodview House
Belfield, Dublin 4
***@***.***
+353 (0) 1 716 3419
